export interface Initiative {
  title: string;
  description: string;
  location: string;
  category: string;
  author: string;
  createdAt: Date;
}

export const initiativesArr: Initiative[] = [
  {
    title: 'Community Cleanup',
    description:
      'Organize a cleanup of the local park to make it more welcoming.',
    author: 'John Doe',
    createdAt: new Date('2024-01-01'),
    location: 'Central Park, NY',
    category: 'Environment',
  },
  {
    title: 'Coding Workshop for Kids',
    description: 'Teach basic coding skills to children in the community.',
    author: 'Jane Smith',
    createdAt: new Date('2024-01-05'),
    location: 'Library Hall, CA',
    category: 'Education',
  },
  {
    title: 'Neighborhood Watch Program',
    description: 'Improve neighborhood safety through regular patrols.',
    author: 'James Brown',
    createdAt: new Date('2024-01-10'),
    location: 'Elm Street, TX',
    category: 'Safety',
  },
  {
    title: 'Food Drive',
    description: 'Collect non-perishable food items for those in need.',
    author: 'Emma Wilson',
    createdAt: new Date('2024-01-12'),
    location: 'Community Center, FL',
    category: 'Charity',
  },
  {
    title: 'Tree Planting Initiative',
    description: 'Plant trees in urban areas to promote greener spaces.',
    author: 'Olivia Johnson',
    createdAt: new Date('2024-01-15'),
    location: 'Downtown, LA',
    category: 'Environment',
  },
  {
    title: 'Fitness Challenge',
    description: 'Organize a group fitness challenge to promote health.',
    author: 'Michael Davis',
    createdAt: new Date('2024-01-20'),
    location: 'Sports Complex, AZ',
    category: 'Health',
  },
  {
    title: 'Art for All',
    description: 'Host an art exhibition showcasing local talent.',
    author: 'Sophia Martinez',
    createdAt: new Date('2024-01-25'),
    location: 'Gallery 21, NY',
    category: 'Arts',
  },
  {
    title: 'Beach Clean-Up',
    description: 'Clean the local beach to protect marine life.',
    author: 'William Garcia',
    createdAt: new Date('2024-01-30'),
    location: 'Ocean View, CA',
    category: 'Environment',
  },
  {
    title: 'Tech Skills Training',
    description: 'Provide tech training for underprivileged individuals.',
    author: 'Isabella Rodriguez',
    createdAt: new Date('2024-02-05'),
    location: 'Tech Hub, TX',
    category: 'Education',
  },
  {
    title: 'Animal Shelter Support',
    description: 'Volunteer at the local animal shelter to care for animals.',
    author: 'Ethan Lee',
    createdAt: new Date('2024-02-10'),
    location: 'Shelter Hope, FL',
    category: 'Charity',
  },
  {
    title: 'Senior Citizen Assistance',
    description: 'Help senior citizens with daily chores and errands.',
    author: 'Ava White',
    createdAt: new Date('2024-02-15'),
    location: 'Sunrise Community, OH',
    category: 'Support',
  },
  {
    title: 'Youth Mentorship Program',
    description: 'Mentor young people to build their confidence and skills.',
    author: 'Mason Thompson',
    createdAt: new Date('2024-02-20'),
    location: 'City Hall, MI',
    category: 'Education',
  },
  {
    title: 'Book Donation Drive',
    description: 'Collect books to donate to local libraries and schools.',
    author: 'Mia Scott',
    createdAt: new Date('2024-02-25'),
    location: 'Library Hall, IL',
    category: 'Charity',
  },
  {
    title: 'Recycling Awareness Campaign',
    description: 'Raise awareness about recycling through workshops.',
    author: 'Lucas Moore',
    createdAt: new Date('2024-03-01'),
    location: 'Community Park, WA',
    category: 'Environment',
  },
  {
    title: 'Volunteer Blood Drive',
    description: 'Organize a blood drive to support local hospitals.',
    author: 'Charlotte Taylor',
    createdAt: new Date('2024-03-05'),
    location: 'Health Center, NY',
    category: 'Health',
  },
  {
    title: 'Small Business Fair',
    description: 'Showcase local small businesses to support the economy.',
    author: 'Logan Anderson',
    createdAt: new Date('2024-03-10'),
    location: 'Town Square, CO',
    category: 'Economy',
  },
  {
    title: 'Music Festival for Charity',
    description: 'Host a music festival to raise funds for a good cause.',
    author: 'Harper Lopez',
    createdAt: new Date('2024-03-15'),
    location: 'Open Grounds, TN',
    category: 'Arts',
  },
  {
    title: 'Language Exchange Program',
    description: 'Promote cultural understanding through language learning.',
    author: 'Jack Adams',
    createdAt: new Date('2024-03-20'),
    location: 'Cultural Center, MA',
    category: 'Education',
  },
  {
    title: 'Mental Health Awareness Walk',
    description: 'Organize a walk to raise awareness about mental health.',
    author: 'Amelia Nelson',
    createdAt: new Date('2024-03-25'),
    location: 'River Park, NC',
    category: 'Health',
  },
  {
    title: 'Green Roof Project',
    description: 'Install green roofs on urban buildings for sustainability.',
    author: 'Henry Carter',
    createdAt: new Date('2024-03-30'),
    location: 'Downtown, IL',
    category: 'Environment',
  },
];
