import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Roboto } from 'next/font/google';
import Footer from './(root)/components/Footer';
import Header from './(root)/components/Header';
import { Toaster } from '@/components/ui/toaster';
import BackToTop from '@/components/BackToTop';
import { AuthProvider } from '@/contexts/AuthProvider';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={roboto.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <div className="flex flex-col min-h-screen isolate">
                <Header />
                <main className="flex-grow">{children}</main>
                <Footer />
              </div>
              <Toaster />
              <BackToTop />
            </AuthProvider>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
